### ISSUE TITLE
Teams Service

### ISSUE THREAD

**Issue by partamonov** [russellcardullo/go-pingdom#24]
Please let me know if anyone is busy with adding `Teams Service` to the client.

I wanna do that shortly, if there are no objections

**Comment by russellcardullo** [comment]
Thanks @partamonov.  No objections here.  I think having that would be great since it would replace the deprecated Contacts service.

**Comment by partamonov** [comment]
good, almost finished, will add users here as well.

**Comment by partamonov** [comment]
Decided to skip users for now, as it's better to wait a little, as API does not support creation of Admin/Editor/Viewer users, only Contact type is supported
