### ISSUE TITLE
Can't include as a dependency when using dep

### ISSUE THREAD

**Issue by jgchristopher** [russellcardullo/go-pingdom#45]
Sorry if this is an obvious issue on my end. I am new to Go dep.
`Solving failure: No versions of github.com/russellcardullo/go-pingdom met constraints:
	master: Could not introduce github.com/russellcardullo/go-pingdom@master, as its subpackage github.com/russellcardullo/go-pingdom does not contain usable Go code (*build.NoGoError).. (Package is required by (root).)
	gomod: Could not introduce github.com/russellcardullo/go-pingdom@gomod, as its subpackage github.com/russellcardullo/go-pingdom does not contain usable Go code (*build.NoGoError).. (Package is required by (root).)
`

**Comment by jgchristopher** [comment]
ugh, nevermind. User error as I expected.

**Comment by russellcardullo** [comment]
@jgchristopher no worries!  I have a PR open to switch from dep to using go modules since that seems to be the direction the go community is moving.

Not sure that helps or makes things worse but LMK if you have any questions about that.
