### ISSUE TITLE
Support for Pingdom 3.1

### ISSUE THREAD

**Issue by jsdidierlaurent** [russellcardullo/go-pingdom#52]
Api 2.1 with old appkey will be deprecated

Are you planning to migrate to 3.1 ?

**Comment by joshsouza** [comment]
@jsdidierlaurent @russellcardullo I've got a fork in which I've updated things to work with the v3.1 API: https://github.com/grnhse/go-pingdom/tree/api-v3.1
It looks like they dropped a lot of functionality from the API in the new version (Not sure if it's coming eventually, or a change in their direction).
I'm also relatively fresh on `golang`, so this totally might not be the direction you want to take things in, but I figured I could save you some time if you wanted to take a look.

My changes are completely not backwards compatible, and I imagine that the actual ideal solution to this would be to allow you to choose which API version you want to use, but at least this gives us a place to start.

**Comment by jsdidierlaurent** [comment]
Your code look's good to me. But i can't use it because module name continue to point on this repository

**Comment by joshsouza** [comment]
There's a way to leverage go modules to work around that, but I'm not sufficiently experienced to be comfortable trying to guide anyone else on how to do it properly.

**Comment by freeseacher** [comment]
any updates ?

**Comment by ehdieunguyen** [comment]
@joshsouza it is better to create a PR on this repo to support Pingdom v3.1. How do you think about my suggestion?

**Comment by bogdanalov-sw** [comment]
Hey guys. Can we get this moving? I can take a trial token and we can test it.

**Comment by joshsouza** [comment]
Sorry, this had fallen off my radar for a while, as we've been running off my fork for a while. I'll see about finding some time to devote to this in the next couple of weeks, but it would not offend me in any way if someone wanted to carry the torch forward until I have the time. I'm sure there's been updates this change would need to account for.

**Comment by freeseacher** [comment]
up

**Comment by russellcardullo** [comment]
This is now merged in #57.
